"""Provider-neutral EvidenceFlow domain contracts."""

from app.domain.documents import (
    DocumentType,
    PageContent,
    ProcessedDocument,
    ProcessorMetadata,
    UploadedDocument,
)
from app.domain.extractions import (
    ApplicationFormExtraction,
    ClarificationStatement,
    CompanyExtractExtraction,
    DocumentClassification,
    EffectiveFieldValue,
    EffectiveValueSource,
    EvidenceReference,
    ExtractedField,
    ExtractionResult,
    FieldValue,
    FinancialStatementExtraction,
    NormalizedValue,
    SupportingCorrespondenceExtraction,
    TypedExtractionResult,
    UnknownDocumentExtraction,
)
from app.domain.findings import (
    Finding,
    FindingEvidence,
    FindingSeverity,
    FindingType,
)
from app.domain.policy import PolicyEvidence
from app.domain.reports import ReportNarrative, ReportSection, ReportStatus, ReviewReport
from app.domain.reviews import (
    ConflictCandidate,
    ExpectedValueType,
    ReviewAction,
    ReviewDecision,
    ReviewDecisionAudit,
    ReviewItem,
    ReviewItemStatus,
    ReviewItemType,
    VerifiedReview,
)

__all__ = [
    "ApplicationFormExtraction",
    "ClarificationStatement",
    "CompanyExtractExtraction",
    "ConflictCandidate",
    "DocumentClassification",
    "DocumentType",
    "EffectiveFieldValue",
    "EffectiveValueSource",
    "EvidenceReference",
    "ExpectedValueType",
    "ExtractedField",
    "ExtractionResult",
    "FieldValue",
    "FinancialStatementExtraction",
    "Finding",
    "FindingEvidence",
    "FindingSeverity",
    "FindingType",
    "NormalizedValue",
    "PageContent",
    "PolicyEvidence",
    "ProcessedDocument",
    "ProcessorMetadata",
    "ReportNarrative",
    "ReportSection",
    "ReportStatus",
    "ReviewAction",
    "ReviewDecision",
    "ReviewDecisionAudit",
    "ReviewItem",
    "ReviewItemStatus",
    "ReviewItemType",
    "ReviewReport",
    "SupportingCorrespondenceExtraction",
    "TypedExtractionResult",
    "UnknownDocumentExtraction",
    "UploadedDocument",
    "VerifiedReview",
]
