"""Typed, provider-aware dependency preparation API."""

from app.preparation.models import (
    CheckOutcome,
    CheckSeverity,
    ModelTask,
    PreparationComponent,
    PreparationMode,
    PreparationReport,
    PreparationResult,
    PreparationStatus,
    SeverityResolver,
    default_failure_severity,
    failed_result,
    passed_result,
    skipped_result,
)
from app.preparation.ollama import (
    OllamaInventoryLoader,
    OllamaReadinessChecker,
    ProviderEndpointError,
    ProviderHTTPError,
    ProviderMalformedResponseError,
    ProviderProbeError,
    ProviderUnreachableError,
    load_ollama_inventory,
    parse_ollama_inventory,
    safe_endpoint_label,
)
from app.preparation.providers import (
    DEFAULT_OLLAMA_BASE_URL,
    ModelRequirement,
    ProviderCheckerRegistry,
    ProviderReadinessChecker,
    model_requirements,
    model_tasks_for_mode,
)
from app.preparation.runtime import (
    PreparationBlockedError,
    mlflow_health,
    prepare_application,
    require_prepared,
)
from app.preparation.service import default_provider_registry, prepare_model_providers

__all__ = [
    "DEFAULT_OLLAMA_BASE_URL",
    "CheckOutcome",
    "CheckSeverity",
    "ModelRequirement",
    "ModelTask",
    "OllamaInventoryLoader",
    "OllamaReadinessChecker",
    "PreparationBlockedError",
    "PreparationComponent",
    "PreparationMode",
    "PreparationReport",
    "PreparationResult",
    "PreparationStatus",
    "ProviderCheckerRegistry",
    "ProviderEndpointError",
    "ProviderHTTPError",
    "ProviderMalformedResponseError",
    "ProviderProbeError",
    "ProviderReadinessChecker",
    "ProviderUnreachableError",
    "SeverityResolver",
    "default_failure_severity",
    "default_provider_registry",
    "failed_result",
    "load_ollama_inventory",
    "mlflow_health",
    "model_requirements",
    "model_tasks_for_mode",
    "parse_ollama_inventory",
    "passed_result",
    "prepare_application",
    "prepare_model_providers",
    "require_prepared",
    "safe_endpoint_label",
    "skipped_result",
]
